### ISSUE TITLE
[Issue] Templates not Loading

### ISSUE THREAD

**Issue by TheKillingJay** [pumbers/journal-templates#2]
Hello your module is exactly the kind of thing I love for documentation! However, I am having trouble having templates loading. Here is an example of what I am trying: 

https://i.imgur.com/lkosUEQ.png

My foundry version is in the photo. Even with no modules the same thing happens.

**Comment by Grygon** [comment]
I had the same issue originally--try putting the templates in "Data/worlds/[world]/journal-templates/" instead.

**Comment by pumbers** [comment]
Yes, the templates must be in `Data/worlds/[world]/journal-templates/` and should be `.html` or `.hbs` files.
