### ISSUE TITLE
Cannot install from mod directory

### ISSUE THREAD

**Issue by apoapostolov** [pumbers/journal-templates#3]
![image](https://user-images.githubusercontent.com/4083812/96987013-17ae2d80-152b-11eb-8690-8423eb77502b.png)

**Comment by pumbers** [comment]
I'm not clear on what you mean by "mod directory"?

Can you let me know your OS (Windows, Mac, Linux) version and your browser. Also, if you can, open up the developer console in your browser then try the install and let me know if you see any errors there.

FYI, I've just updated the module for Foundry VTT 0.7.x as well.

**Comment by pumbers** [comment]
Closing,no further information received.
