### ISSUE TITLE
"no templates defined" despite templates being defined

### ISSUE THREAD

**Issue by scooper4711** [pumbers/journal-templates#4]
Running foundry 0.7.8
Trying to get this to work. I made one simple template, and also copied over your test01.html template to my world's directory "journal-templates"
I see the following in the console:
```
Foundry VTT | Retrieved and compiled template modules/gm-screen/templates/parts/compact-journal-entry.hbs
foundry.js:5869 Foundry VTT | Loaded localization file modules/journal-templates/lang/en.json
foundry.js:5961 Foundry VTT | Retrieved and compiled template templates/sidebar/journal-directory.html
main.js:13268 Journal Templates | Initializing
main.js:13274 Journal Templates | Loading from worlds/harn/journal-templates
main.js:13296 Journal Templates | Loaded worlds/harn/journal-templates/test01.html
main.js:13296 Journal Templates | Loaded worlds/harn/journal-templates/ritual.html
main.js:13324 Journal Templates | Loaded (2) ["Ritual Invocation", "Some Template"]
```
but when I press the icon to insert a template, I get the message "no templates defined"

**Comment by scooper4711** [comment]
I also get a message upon launching the world that two templates were defined. But when I try to use them, zilch.

**Comment by pumbers** [comment]
Hi, sorry for taking a while to spot this but my notifications from Github are a bit unreliable. I'll take a look at it and see what I can find.

**Comment by pumbers** [comment]
I couldn't duplicate this specific problem, but I was getting a weird error message when creating a new journal entry that appears to be a change in the Foundry function that I was hooking in to that could be causing a problem. I've updated the code to remove that error and added some additional logging that shows (in the console) how many templates are available at then time the editor widow opens as a double-check. Let me know if you're still getting the problem and what that new message shows when you do.

**Comment by scooper4711** [comment]
This seems to have resolved it. Thanks!

**Comment by scooper4711** [comment]
Since you mentioned that your GitHub notifications were unreliable, here’s an email about a feature request I’ve opened.
https://github.com/pumbers/journal-templates/issues/6 <https://github.com/pumbers/journal-templates/issues/6>
