### ISSUE TITLE
Specify template folder

### ISSUE THREAD

**Issue by Rattercrash** [pumbers/journal-templates#5]
It would be a nice feature to be able to specify the template folder, so that a) multiple worlds can share the same templates, and b) users of Forge or similar hosting services can upload templates more easily by specifying a folder in the Assets subsection.

**Comment by pumbers** [comment]
I'll take a look at it, thanks for the suggestion.

**Comment by pumbers** [comment]
Added a module setting for the template location folder, defaults to `journal-templates` in the the current world folder.
